### ISSUE TITLE
The reason why conjure-daily took 10 hours

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure#212]
Originally reported by: **Bilal Hussain (Bitbucket: [Bilalh](https://bitbucket.org/Bilalh), GitHub: [Bilalh](https://github.com/Bilalh))**

---

`02-set.essence` seem to be problem  since it the only test to take over an hour and a half (it took 10 hours)

```
language Essence 1.3

given a,b : set of int(0..5)
find x : set of int(0..5)
such that x = a intersect b
```

Is there some way of changing the spec so it does not take as long?

The tests that took the longest are: 

```
583m37.351s
/Users/hudson/workspace/conjure-daily/test/solving/02-set/02-set.essence df

100m10.354s
/Users/hudson/workspace/conjure-daily/test/solving/_trivial/matrixes5/matrixes5.essence df-compact-param

98m0.970s
/Users/hudson/workspace/conjure-daily/test/solving/_trivial/matrixes5/matrixes5.essence df

81m11.045s
/Users/hudson/workspace/conjure-daily/test/solving/relation_2_ints-1/relation_2_ints-1.essence df-compact-param 

79m13.393s
/Users/hudson/workspace/conjure-daily/test/solving/relation_2_ints-1/relation_2_ints-1.essence df


```

---
- Bitbucket: https://bitbucket.org/stacs_cp/conjure-old/issue/211

**Comment by ott2** [comment]
Is this still an issue?

The original set intersection model now seems rather quick to process.

**Comment by ozgurakgun** [comment]
@ott2 probably not. Let me add a regression test and close the issue. Thanks for checking!

**Comment by ozgurakgun** [comment]
Oh, I remember this now. It generates several models (in the testing setup), hence it takes a long time. It doesn't take as long as it was initially reported though!

For the record, this takes ~1 minute to generate 64 models.

**Comment by ozgurakgun** [comment]
Closing without the regression test.
