### ISSUE TITLE
dontCare produces unsolvable problems

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure#350]
The following problem seems to be unsolvable. Am I missing understanding?

```
language ESSENCE 1.0

$ Original problem variables
find S : set (size 5) of int(1..50)

such that
dontCare(S)
```

**Comment by ozgurakgun** [comment]
This did occur to me the other day, but I wasn't sure.

`dontCare` will not respect the structural constraints. Assuming the set is represented using explicit, it would set `S_explicit` to `[1,1,1,1,1]`. Which of course contradicts with the structural constraints.

When Conjure introduces `dontCare`s it makes sure to only post them when we truly do not care, and then it also guards the structural constraints.

I am not sure what we would want to do, as in what would you expect the solution to be to this problem? Something like {1,2,3,4,5}?

**Comment by ChrisJefferson** [comment]
Yes, I would say just any valid assignment to the set (this of course assumes the domain is non-empty. Mine always will be).

We could give in another name, like `domainMin`, then write `S = domainMin(S)` (or something similar..), and assign it the smallest value in the domain (which is easy to figure out) if you want to seperate this from true `dontCare`.

**Comment by ozgurakgun** [comment]
Yes we should keep `dontCare` as is.

`domainMin` could similarly be a constraint that you just post on a variable, unless you have some other use case for it. So you could just say `domainMin(S)`.

I am not sure at the moment if implementing it is actually trivial considering we would need to do this at the class level. Maybe we can have a chat tomorrow.

**Comment by ozgurakgun** [comment]
Since we decided to leave dontCare as is, and we haven't decided for a new syntax for the "new thing" yet, I'll close this issue. Let me know if you need any support from Conjure.

(We could ban dontCare from the input language, but I'll leave it as is for now.)
