### ISSUE TITLE
Produce a warning: optimisation + multiple solutions

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure#351]
Conjure (silently) ignores the request to find multiple solutions when solving an optimisation model. We should produce a warning.

**Comment by ott2** [comment]
As an aside here is an optimisation model where multiple solutions are found, *unless* the ``-O0`` flag is passed to Savile Row.

```
language Essence 1.3
$ test for ST-connectivity, 1 to n, directed graph presented as relation
letting n be 7
letting G be relation ((1,5),(5,7),(3,2),(4,3),(4,6),(6,7))
letting vertices be domain int(1..n)
find M : matrix indexed by [vertices] of bool
find stconnected : bool
such that
  M[1],
  forAll e in G . M[e[1]] -> M[e[2]],
  stconnected = M[n]
minimising toInt(stconnected)
```

``conjure solve -ac --number-of-solutions=all``: 7 solutions
``conjure solve -ac --number-of-solutions=all --savilerow-options -O0``: 1 solution
