### ISSUE TITLE
NameResolution glitch

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#352]
With version 9d707df (2017-05-19 16:19:33 +0100), the following snippet

---
language Essence 1.3
  letting myDomain be domain int
  letting mySet be domain set of myDomain
  find A : mySet
 ---

yields the error:

---
[...]
resolveD Alias Domain

CallStack (from HasCallStack):
  error, called at src/Conjure/Bug.hs:21:15 in conjure-cp-2.0.0-LL815bXO5GTFuBqeLzrcT:Conjure.Bug
  bug, called at src/Conjure/Language/NameResolution.hs:246:58 in conjure-cp-2.0.0-LL815bXO5GTFuBqeLzrcT:Conjure.Language.NameResolution

**Comment by ott2** [comment]
Replacing the "find" by "given":

---
language Essence 1.3
  letting myDomain be domain int
  letting mySet be domain set of myDomain
  given X : set of mySet

---

yields

---
BUGFAIL at calcDummyElem
rule_DomainMinMax.maxOfDomain []

CallStack (from HasCallStack):
  error, called at src/Conjure/Bug.hs:21:15 in conjure-cp-2.0.0-LL815bXO5GTFuBqeLzrcT:Conjure.Bug
  bug, called at src/Conjure/Bug.hs:35:26 in conjure-cp-2.0.0-LL815bXO5GTFuBqeLzrcT:Conjure.Bug

---

Note that replacing the "int" by "int(0..9)" allows Conjure to proceed without problems, with both "given" and "find" present.

**Comment by ozgurakgun** [comment]
Terrible error message in either case, sorry!

In the case of a find, it should complain about an infinite domain. In the case of a given, it is indeed a bug. I'll have a look.

**Comment by ozgurakgun** [comment]
@ott2 can you check if this was really fixed, please?
