### ISSUE TITLE
possible scoping confusion

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#358]
language Essence 1.3
$ bug: possible scoping confusion
letting D be domain int(0..9)
letting C be {0,1,3,4,5,6,7,8}

find y : D such that forAll x : D . ((x < y) -> x*x in C)
$ y=0,1,2,3

find x : D such that exists i : D . x = i*i
$ x=0,1,4,9

**Comment by ott2** [comment]
In contrast, this works (replace the x in the second `find` by z):

language Essence 1.3
$ possible scoping confusion is averted
letting D be domain int(0..9)
letting C be {0,1,3,4,5,6,7,8}

find y : D such that forAll x : D . ((x < y) -> x*x in C)
$ y=0,1,2,3

find z : D such that exists i : D . z = i*i
$ z=0,1,4,9

**Comment by ott2** [comment]
Precise error from Savile Row:
```
ERROR: In comprehension matrix: [((x<y) -> or([(0=(x * x)), (1=(x * x)), (3=(x * x)), (4=(x * x)), (5=(x * x)), (6=(x * x)), (7=(x * x)), (8=(x * x));int(1..8)]))|x : int(0..9), () ;int(1..)]
ERROR: Decision variable in domain.
ERROR: Failed type checking after substituting in lettings.

**Comment by ozgurakgun** [comment]
I get a different error from SR, with the latest commit on the savilerow branch (9ced0dc778fa).

```
Savile Row stdout: ERROR: In matrix comprehension: [((x<y) -> or([(0=(x * x)), (1=(x * x)), (3=(x * x)), (4=(x * x)), (5=(x * x)), (6=(x * x)), (7=(x * x)), (8=(x * x))]))|x : int(0..9), () ;int(1..)]
ERROR: Variable `x' is already defined.
ERROR: Failed type checking after substituting in lettings.
```

There is indeed a reused variable name in the output.


@pwn1 - I should know this but does SR really not allow any name shadowing at all? Following is a minimal "failing" case.

```
language ESSENCE' 1.0

find x: int(0..9)
such that and([x=1 | x : int(0..9)])
```

**Comment by pwn1** [comment]
The intention is that shadowing is not allowed. 

I can imagine that if I missed a check somewhere, and let through something like your example, that it might work because references to x inside the comprehension would be dealt with by the comprehension.

**Comment by ozgurakgun** [comment]
It doesn't go through, it gives an error similar to the one in my previous message.

**Comment by ott2** [comment]
Is the precise issue that SR treats `find` variables as globals?  If so we could for the moment mention this in the Conjure docs (something like "avoid using the same variable name both as a decision variable in a find, and for quantification").

**Comment by ozgurakgun** [comment]
I think we should fix this properly. Thanks for documenting the current behaviour though @ott2.
