### ISSUE TITLE
conjure solve wants unsupported Savile Row commandline argument

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#359]
Latest Conjure and latest SR fail to interoperate with `solve`.  In more detail:

`touch empty.essence; conjure solve empty.essence` with `8f80bab (2017-06-19 16:14:45 +0100)` yields:
```
...
savilerow -in-eprime conjure-output/model000001.eprime -out-minion conjure-output/model000001.eprime-minion -out-sat conjure-output/model000001.eprime-dimacs -out-aux conjure-output/model000001.eprime-aux -out-info conjure-output/model000001.eprime-info -run-solver -solutions-to-stdout-one-line -num-solutions 1 -minion
which savilerow
...
Savile Row stdout: Savile Row 1.6.4 (Repository Version: 9ced0dc778fa (2017-06-19 15:29 +0100))
...
Savile Row stderr: ERROR: Failed to parse the following argument: -solutions-to-stdout-one-line
...
```
The string `-solutions-to-stdout-one-line` is in `src/Conjure/UI/MainHelper.hs` whereas SR seems to use `-solutions-to-stdout` without the final suffix.  Perhaps this changed in SR at some stage?

**Comment by ozgurakgun** [comment]
I thought we talked about this? I added that flag to SR after the latest release.

**Comment by ott2** [comment]
Replacing the string in `MainHelper.hs` with the shorter one seems to fix the immediate issue; `conjure solve --number-of-solutions=all issue-conjure-358-scoping-b.essence` yields 16 solutions as expected.

**Comment by ott2** [comment]
@ozgurakgun if you are using a version of SR that is private, then apologies; I thought you meant that SR had added that flag after 1.6.4, which is why I was testing with tip.

However, a public conjure-head should proably not be using flags not in any current SR?

**Comment by pwn1** [comment]
Andras, you need the tip of the branch named savilerow, not journalexp

**Comment by ott2** [comment]
@pwn1, thanks for the "tip" top tip.  (The option was added in r2181 in 2015, although unmentioned in -help, but I was using the wrong branch.)  I confirm this works with current Conjure and SR, closing.
