### ISSUE TITLE
inconsistent error messages

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#361]
Consider the following snippet that finds the minimum:
```
language Essence 1.3
letting V be domain int(1..2)
find x : V such that forAll j : V . x <= j
```
When incorrectly using `in` instead of `:`, the following yields a cryptic `Error: innerTypeOf: TypeInt`:
```
language Essence 1.3
letting V be domain int(1..2)
find x : V such that forAll j in V . x <= j
```
Contrast with the same code that has the `V` alias inlined:
```
language Essence 1.3
find x : int(1..2) such that forAll j in int(1..2) . x <= j
```
which yields the error `expecting comma, end of input, operator, rest of statement, or statement`.

It would be nice if these yielded error messages that were vaguely comparable.

**Comment by ott2** [comment]
With the recent changes, the first error message is now much improved.  It now says
```
Error:
    In a 'such that' statement: and([x <= j | j <- V])
    Error:
        Type error in the generator of a comprehension or a quantified expression
        Consider using j : V
```
The second snippet returns
```
Error:
    issues/issue-conjure-361-in-b.essence:2:37:
unexpected j
expecting comma, end of input, operator, rest of statement, or statement
    find x : int(1..2) such that forAll j in int(1..2) . x <= j
                                        ^
```
The first error is probably more useful in form.

On the other hand, the second form indicates the place in the input where the error has been located, while keeping the input as is.  In contrast, the first reports the error relative to a comprehension that does not explicitly appear in the input.

It would still be nice to have similar errors whether aliases are used or not, but the remaining part to be done is probably a minor enhancement or feature request.

**Comment by ozgurakgun** [comment]
The difference is that without an alias this is a parsing error, and with an alias, it is a type error.

**Comment by ott2** [comment]
(Not sure whether this belongs here or in #133 or in a new issue, since this relates to a syntax error that appears to have nothing to do with typing, but that leads to inconsistent messages depending on whether a macro-like construct is used or not.)

With ``1a3bebb (2017-06-23 21:54:49 +0100)`` a somewhat similar inconsistency occurs when garbling `!=` as `<>` in an expression, depending on whether this happens in a `forAll` or a comprehension:
```
> cat issue-garbled-ineq-a.essence; conjure solve -ac issue-garbled-ineq-a.essence
language Essence 1.3
find i : int(0..9) such that forAll j : int(0..9) . j <> i

Error:
    issue-garbled-ineq-a.essence:2:37:
unexpected j
expecting comma, end of input, operator, rest of statement, or statement
    find i : int(0..9) such that forAll j : int(0..9) . j <> i
```
which is quite misleading (the `j` is not the problem, the bad token is) versus the rather more helpful
```
> cat issue-garbled-ineq-b.essence; conjure solve -ac issue-garbled-ineq-b.essence
language Essence 1.3
find i : int(0..9) such that and([j <> i | j : int(0..9)])

Error:
    issue-garbled-ineq-b.essence:2:38:
unexpected >
expecting expression
    find i : int(0..9) such that and([j <> i | j : int(0..9)])
                                         ^
```

**Comment by ozgurakgun** [comment]
I think the last point is important, we should create a new issue for it. It is to do with the parsing of quantified expressions.

I am closing this one since I think the error messages for the original post are improved now. Please reopen if you disagree.
