### ISSUE TITLE
incorrect evaluation of logical expression

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#364]
With conjure 1a3bebb (2017-06-23 21:54:49 +0100),
```
language Essence 1.3
find c : bool such that c = true /\ (!true)
```
yields the unsatisfiable model ``find c:bool such that false`` whereas
```
language Essence 1.3
find c : bool such that c = false
```
yields a model ``find c:bool such that c=false``, as expected.

**Comment by ozgurakgun** [comment]
It is a parsing issue, it parses as `such that (c = true) /\ (!true)`.

I think SR also parses it the same way, doesn't it?

**Comment by ChrisJefferson** [comment]
I think `c = true /\ (!true)` is parsed as `(c = true) /\ (!true)`.

**Comment by ott2** [comment]
Confirmed that
```
find c : bool such that c = (true /\ (!true))
```
has a solution, closing.
