### ISSUE TITLE
Improve error reporting for quantified expression parsing

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure#365]
@ott2 reports this in #361 - copying here.

--------

(Not sure whether this belongs here or in #133 or in a new issue, since this relates to a syntax error that appears to have nothing to do with typing, but that leads to inconsistent messages depending on whether a macro-like construct is used or not.)

With ``1a3bebb (2017-06-23 21:54:49 +0100)`` a somewhat similar inconsistency occurs when garbling `!=` as `<>` in an expression, depending on whether this happens in a `forAll` or a comprehension:
```
> cat issue-garbled-ineq-a.essence; conjure solve -ac issue-garbled-ineq-a.essence
language Essence 1.3
find i : int(0..9) such that forAll j : int(0..9) . j <> i

Error:
    issue-garbled-ineq-a.essence:2:37:
unexpected j
expecting comma, end of input, operator, rest of statement, or statement
    find i : int(0..9) such that forAll j : int(0..9) . j <> i
```
which is quite misleading (the `j` is not the problem, the bad token is) versus the rather more helpful
```
> cat issue-garbled-ineq-b.essence; conjure solve -ac issue-garbled-ineq-b.essence
language Essence 1.3
find i : int(0..9) such that and([j <> i | j : int(0..9)])

Error:
    issue-garbled-ineq-b.essence:2:38:
unexpected >
expecting expression
    find i : int(0..9) such that and([j <> i | j : int(0..9)])
                                         ^
```

**Comment by ott2** [comment]
This again bit me, trying to use ``<=>`` instead of ``<->``.  I had to systematically replace all tokens by hand to isolate the problem in a complex expression, wasting half an hour.
