### ISSUE TITLE
"not refined": iterating over graph edges

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#371]
With 01ae4b3 ``(2017-07-12 22:58:02 +0100)``,
```
letting G be {{1,2},{1,4}}
find w : int(1..4) such that forAll {u,v} in G . w in {u,v}
```
fails with "not refined" for G, while the identical semantics
```
letting G be {{1,2},{1,4}}
find w : int(1..4) such that forAll u,v : int(1..4) . ({u,v} in G) -> (w in {u,v})
```
works fine.  If this style of quantification is not supported, then it should be deprecated in the documentation.

**Comment by ozgurakgun** [comment]
I can reproduce this, but cannot look at it now. Or at least I shouldn't! :)

You could use the following though, which works.

```
letting G be {{1,2},{1,4}}
find w : int(1..4) such that forAll edge in G . w in edge
```

**Comment by ott2** [comment]
Indeed it does.  Thanks!  Alas, the original model this came from doesn't permit this trick, as the actual constraint is more complex (this was cut down from a larger model to isolate the issue).
