### ISSUE TITLE
matrix equality test glitch?

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#373]
In the following snippet
```
letting E be domain matrix indexed by [int(1..2)] of int(0..2)
letting D1 be domain matrix indexed by [int(1..2)] of E
letting D2 be domain matrix indexed by [int(1..2),int(1..2)] of int(0..2)
find A : D1 such that A[1] = [0,1], A[2] = [1,2]
find B : D2 such that B = [[0,1],[1,2]]
find a : bool such that a = (A=B)
find b : bool such that b = ((A[1]=B[1]) /\ (A[2]=B[2]))
find c : bool such that c = ([A[1],A[2]] = [B[1],B[2]])
find d : bool such that d = ([[0,1],[1,2]] = [[0,1],[1,2]])
find e : bool such that e = ([A[1]] = [B[1]])
find f : bool such that f = ([A[1],[1,2]] = [B[1],[1,2]])
```
I was expecting all the Boolean decision variables to be set to `true`, but `c` and `f` are set to `false` in the unique solution.

**Comment by ozgurakgun** [comment]
I managed to boil this down to the following E'.

```
language ESSENCE' 1.0

find A: matrix indexed by [int(1..2), int(1..2)] of int(0..2)
such that
    forAll i, j : int(1..2) .
        A[i, j] = [A[1, ..], A[2, ..]][i, j]
```

Which has `A` replaced with `[A[1, ..], A[2, ..]]` on the RHS. I will raise it with @pwn1 - let's see if we are missing something.

**Comment by ozgurakgun** [comment]
@ott2 : By the way, if you put the snippet in a file called `373.essence` and run `conjure solve 373.essence --validate-solutions` flags the problem.

```
~/repos/github/conjure> conjure solve 373.essence --validate-solutions
Generating models for 373.essence
Generated models: model000001.eprime
Saved under: conjure-output
Savile Row: model000001.eprime
Validating solution: conjure-output/model000001-solution000001.solution
Error:
    Invalid.
        Statement evaluates to: false
        Original statement was: c = ([A[1], A[2]; int(1..2)] = [B[1], B[2]; int(1..2)])
        Relevant values:
            letting c be false
            letting B be [[0, 1; int(1..2)], [1, 2; int(1..2)]; int(1..2)]
            letting A be [[0, 1; int(1..2)], [1, 2; int(1..2)]; int(1..2)]
```

**Comment by ott2** [comment]
Interesting.  What does the ``..`` syntax mean in an array context?

**Comment by ozgurakgun** [comment]
Slicing. Section 2.7 in the Essence Prime description document explains them, I think.

**Comment by ozgurakgun** [comment]
For the record: this is a confirmed Savile Row bug, we are waiting for a fix. I will add a regression test once it is fixed.

**Comment by pwn1** [comment]
Should be fixed in Savile Row on the head of the savilerow branch.

**Comment by ozgurakgun** [comment]
Lovely. I'll update the unreleased Savile Row version we use for testing, and then add a regression test. Thanks!

**Comment by ott2** [comment]
Documentation needs to be updated.

**Comment by ozgurakgun** [comment]
Can we somehow make sure to remember to update the documentation when a new SR release is made?
