### ISSUE TITLE
in max expansion, guarding expression turns into conjunct

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#382]
From @SaadAttieh, confirmed:

Essence input:
```
find a : function (total) int(1..2) --> int(1..2)
find b : int(1..10)
such that
$force function to be non surjective:
a(1) = 1,
a(2) = 1,
$problematic expression:
b = sum i : int(1..2) . max([v | (_,v) <- a, v = i])
```

This produces no solutions but it should.

Eprime output with comment  below regarding incorrect expression refinement:
```
language ESSENCE' 1.0

find a_Function1D: matrix indexed by [int(1..2)] of int(1..2)
find b: int(1..10)
find conjure_aux1: matrix indexed by [int(1..2)] of int(1..2)
such that
    a_Function1D[1] = 1,
    a_Function1D[2] = 1,
    and([and([a_Function1D[q3] = i -> a_Function1D[q3] <= conjure_aux1[i] | q3 : int(1..2)]) | i : int(1..2)]),
    and([or([a_Function1D[q3] = i /\ a_Function1D[q3] = conjure_aux1[i] | q3 : int(1..2)]) | i : int(1..2)]),
    b = sum([conjure_aux1[i] | i : int(1..2)])
```

The condition ``v = i`` in the expression
``b = sum i : int(1..2) . max([v | (_,v) <- a, v = i])``
is being pushed into the exists:
``and([or([a_Function1D[q3] = i /\``
(taken from second last line of eprime).
The expression should be an implication not an and. i.e.
``and([or([a_Function1D[q3] = i ->``

The fact that it is an “and” is forcing the function to be surjective.  Conjure is saying, forAll i there is something in the function that maps to i.

**Comment by ozgurakgun** [comment]
cc @SaadAttieh 

This is actually not a bug!

Let me unroll your problematic expression by hand first.

```
b = max([v | (_,v) <- a, v = 1]) + max([v | (_,v) <- a, v = 2])
```

Now notice that the second list comprehension generates an empty list.

`max([])` is undefined, Under the relational semantics, nearest containing relational expression will be false. That expression happens to be at the top level, hence the whole model is UNSAT.


---

However, since you are such good customers, I will give you another snippet which has a bug.

```
find t : bool
such that t <-> (b = max([v | (_,v) <- a, v = 2]))
```

The above essence is also UNSAT currently, and it shouldn't be!

Is this more like what you had in mind?

**Comment by SaadAttieh** [comment]
Oz 1, Saad/Andras 0. :)


No, I think we were incorrect in deciding that the first was a bug.  We both looked at the essence for a while and never arrived at that conclusion.  Should catchUndef work in this situation? that is 
sum(catchUndef(max…, 0))

I think I’m going to start a hashtag #undefinedEssence

**Comment by ozgurakgun** [comment]
Well, there is still a bug here, so I am not sure if I deserve the 1 point.

`catchUndef` should work, but won't, due to the same bug. If this is blocking, can you please send me the actual Essence we need in an email and we can see if there is a workaround.

**Comment by SaadAttieh** [comment]
Essence below, hope pasting text here is okay.  
We need it for the minimum energy broadcast problem.
Some notes about the problem structure:
We use a function from child to parent to enforce a tree structure.
We use a function that maps nodes to their depths to enforce acyclic constraint.
We are given a function that gives us the cost of every parent -> child connection.
The problematic expression comes from the objective
totalCost = sum p over all parents . max(all connections going from p
)


language Essence 1.3

given numberNodes : int(1..)
given initialNode : int(1..numberNodes)
letting dNodes be domain int(1..numberNodes)
letting dDepths be domain dNodes
$ if a node has power link of 0 to another node, that link is not possible
given linkCosts : function (total) (dNodes,dNodes) --> int(0..)


find parents : function (total) dNodes --> dNodes
find depths : function (total) dNodes --> dDepths
such that
parents(initialNode) = initialNode
, forAll (child,parent) in parents .
    (child != initialNode) -> 
    (parent != child /\ linkCosts((parent,child)) != 0)
such that forAll (child,parent) in parents .
    child != initialNode -> depths(child) > depths(parent)


find totalCost : int(0..numberNodes * max([cost | (_,cost) <- linkCosts]))
such that
totalCost = sum parent : dNodes .
    max([linkCosts((parentI,child)) | (child,parentI) <- parents, parentI = parent ])

**Comment by ott2** [comment]
Quite possibly related, ``preImage(f,y)`` seems to fail rather than return an empty set if there is no ``x`` such that ``f(x) = y``.  The canonical Essence specification states:

``preimage(F,v)`` denotes the set ``{y|F(y)=v}``.

which I interpret as "when there is no element in the preimage, then return the empty set", not "fail if there are no elements".

**Comment by ozgurakgun** [comment]
The one I gave is indeed a bug, because the nearest containing Boolean should become false, which is the right-hand-side of the `<->`. It's the same issue with catchUndef.

**Comment by ott2** [comment]
I'm probably misinterpreting the actual Essence here.  I thought you meant "replace the last line with the following last line"?  In this case the filter is always false (the only value that ``a`` takes is 1), so the expression is of the form ``max({})`` which is undefined.  (More precisely, ``max({1} intersect {2})`` since there is no way to specify a missing type for an empty set.)

**Comment by ott2** [comment]
To be completely precise:
```
find a : function (total) int(1..2) --> int(1..2)
find b : int(1..10)
such that a(1)=1,a(2)=1
find t : bool
such that t <-> (b = max([v | (_,v) <- a, v = 2]))
```
is unsat, because the ``max`` is applied to an empty set.

```
find a : function (total) int(1..2) --> int(1..2)
find b : int(1..10)
find t : bool
such that t <-> (b = max([v | (_,v) <- a, v = 2]))
```
has a solution, as expected.

```
find S : set of int(1..2) such that S = {1} intersect {2}
find t : int(0..2) such that t = catchUndef(max(S),0)
```
has no solutions, while
```
letting S be {1} intersect {2}
find t : int(0..2) such that t = catchUndef(max(S),0)
```
has solution 0.
