### ISSUE TITLE
incorrect solution (and overly lax typing of unnamed type)

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#383]
The following is a specification of graph colouring.
```
language Essence 1.3
given n : int
letting vertices be domain int(1..n)
given G : set of set (size 2) of vertices

letting colours be new type of size n
find f : function vertices --> colours
such that forAll e in G . f(min(e)) != f(max(e))

find c : int(1..n) such that c = |toSet([ f(u) | u : vertices ])|
minimising c
```

Conjure comes up with a solution consisting of a listing of the unnamed type `colours` (I wasn't expecting this, but whatever), a nice optimal 3-colouring of my 50-vertex input graph, and `letting c be 50` (which is wrong and not what I was expecting).

If contrast, if one replaces the last two lines by
```
find S : set of colours such that S = toSet([ f(u) | u : vertices ])
minimising |S|
```
then as expected `letting S be {colours_1, colours_2, colours_3}`.

Further, if one now replaces the last two lines by
```
find c : colours such that c = |toSet([ f(u) | u : vertices ])|
minimising c
```
then the solution contains `letting c be colours_50` and there is no type error flagged (although I was expecting this to be flagged, since the type of the cardinality operator is integer, and this should not match an unnamed type).

**Comment by ozgurakgun** [comment]
Hi @ott2 

I am trying to reproduce this. Can you add a parameter file as well please?

**Comment by ozgurakgun** [comment]
I think I'll just close the issue, but _please_ reopen if you can reproduce @ott2.

**Comment by ott2** [comment]
The first error is now fixed.  The third spec now gives a type error, which is good, but it is a bit mysterious:
```

**Comment by ozgurakgun** [comment]
Did you mean to paste the error message?

**Comment by ozgurakgun** [comment]
Oh you have pasted the error, sorry! It wasn't included in the email.

**Comment by ozgurakgun** [comment]
The error message is now fixed. Unfortunately, v2.3.0 will produce the mysterious error message. :(
