### ISSUE TITLE
|toSet(list)| yields incorrect value if used in intermediate expression?

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#388]
Trying to compute cardinality of ranges manually (to avoid problems with ``range``; see also #383 which is in the same semantic region), I ran into this:

```
language Essence 1.3
letting vertices be domain int(1..10)
find X : matrix indexed by [vertices] of vertices
such that X = [2,3,1,2,3,1,2,3,1,2]
find c : vertices such that c = |toSet([X[u] | u : vertices])|
```

I was expecting c=3, but getting c=10; eprime model hardcodes c=10!  The error seems to be introduced here (note that ``-ai`` only provides one possible answer for each question):
```
     Answer 1: set-card: Horizontal rule for set cardinality.
              sum([1 | q2 <- toSet([X[u] | u : int(1..10)])])
```

In contrast, the following works fine with ``-ac``:
```
language Essence 1.3
letting vertices be domain int(1..10)
find X : matrix indexed by [vertices] of vertices
such that X = [2,3,1,2,3,1,2,3,1,2]
find C : set of vertices such that C = toSet([X[u] | u : vertices])
find c : vertices such that c = |C|
```

where the only difference between these two specifications is that in the second one, ``C`` is first computed explicitly, then its cardinality is found.

**Comment by ozgurakgun** [comment]
Good news: I think I fixed this. Bad news: it involves the addition of an auxiliary set variable.

I will push the fix after I run the tests.
