### ISSUE TITLE
type error silently suppressed, leading to wrong result?

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#390]
The following snippet
```
find s : int(0..200)
such that s = |toSet([ x | x : int, x = x ])|
```
returns 0 (but no error), whereas
```
find s : int(0..200)
such that s = |toSet([ x | x : int(1..10), x = x ])|
```
returns 10, as expected.

I think either the first should return an error, or 200, but not 0.

**Comment by ozgurakgun** [comment]
Hi @ott2 -- this was just a missing sanity check. Thanks for flagging it!
