### ISSUE TITLE
Simplify ExplicitVarSizeWithMarker

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure#392]
On ExplicitVarSizeWithMarker.hs:

```
forAll &iPat : int(1..&maxSize) .
                                forAll &jPat : int(&i+1..&maxSize) .
                                     &i <= &marker /\ &j <= &marker -> &values[&i] != &values[&j]
```

The `&i <= &marker` isn't required.

**Comment by pwn1** [comment]
Should it be an allDiffExcept?

**Comment by ozgurakgun** [comment]
I can't see that [here](https://github.com/conjure-cp/conjure/blob/2858225340b587a6b03e92a031c8982c45350001/src/Conjure/Representations/Set/ExplicitVarSizeWithMarker.hs), instead there is a version which uses `.<` -- what am I missing?

**Comment by SaadAttieh** [comment]
not sure if relevant, but I believe Chris was looking for errors in neighbourhood modelling. So this stuff would have to be on the sns branch.   

Regards, 
Saad

**Comment by ozgurakgun** [comment]
Thanks Saad, that helps.

**Comment by ChrisJefferson** [comment]
Ah, that could be whats going on. Im looking at weird outputs. This one is only littke of course.

**Comment by ozgurakgun** [comment]
We now produce an allDiff for sets of ints.

I have also fixed the original point @ChrisJefferson, for set of more complex types.

For ExplicitVarSizeWithFlags (the one with boolean flags instead of a single marker) we cannot apply the same trick though. Since the flags are not ordered.

**Comment by ozgurakgun** [comment]
This seems to be fixed, looking at my last comment here. Please reopen if not.
