### ISSUE TITLE
matrix indexing failures

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#396]
The following snippet is sent to Savile Row, which complains:

```
letting I be domain tuple(int(1..2),int(1..2))
find M : matrix indexed by [I] of bool
such that true
```

while the following generates rather unhelpful Conjure errors:

```
letting I be domain tuple(int(1..2),int(1..2))
find M : matrix indexed by [I] of bool
such that forAll u,v : I . M[u] = M[v]
```

If matrices in Essence are supposed to be indexed only by domains of special form, then I think this should be enforced, with appropriate errors.  OTOH, if matrix indexing should work for any totally ordered domain (tuples are usually assumed to be totally ordered by the lex ordering) then this possibly indicates a bug.

Either interpretation seems reasonable; I'd be happy to update the documentation either way.

**Comment by pwn1** [comment]
I thought matrices were only indexed by integer domains.

**Comment by ChrisJefferson** [comment]
I agree. In Essence, one may as well use a function whenever one wants a more complicated domain.

Don't we also allow indexing matrices by matrices?

**Comment by pwn1** [comment]
We do allow indexing matrices by matrices in Essence Prime, possibly not Essence.  Also it's only the case where a matrix is indexed by a single matrix domain and no other domains.

**Comment by ozgurakgun** [comment]
I could make this work easily, but I agree with Chris that we should keep matrices simple. Why not use a function here? If it maps tuples to booleans, you might even use a relation instead.

I can add a better error message, let's leave the issue open until I do that.

**Comment by ozgurakgun** [comment]
Closing the issue, would be great if you want to update the documentation Andras.
