### ISSUE TITLE
type checking allows invalid enum / type of size expressions

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure#398]
Conjure allows various invalid expressions involving enums and type of size expressions:

Use in arithmetic expressions.

Further, type of size should also not be allowed in:

Comparison with < and other ordering operators.

Quantification inside matrix comprehension (this might require some planning, as it is legal in some situations, if we then sum the matrix for example).

**Comment by ozgurakgun** [comment]
Just to confirm this: yes, I was being overly lax with the type-checking of enums and unnameds, they are bundled together with ints currently. Shouldn't be too hard to fix, and I agree we should.

**Comment by ozgurakgun** [comment]
This should be fixed thanks for @fraser-dunlop's tagged-ints work. Please reopen if there is a problem!
