### ISSUE TITLE
Simplify/fix SEND+MORE=MONEY example

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure#399]
We need to update the example. How does this one look?

```
language Essence 1.3
letting letters be new type enum {S,E,N,D,M,O,R,Y}
find f : function (total, injective) letters --> int(0..9)
such that
                 1000*f(S) + 100*f(E) + 10*f(N) + f(D) +
                 1000*f(M) + 100*f(O) + 10*f(R) + f(E) =
    10000*f(M) + 1000*f(O) + 100*f(N) + 10*f(E) + f(Y),
    f(S) > 0, f(M) > 0
```

/cc @ott2

**Comment by ott2** [comment]
Looks good, but will have to revise the text as the complicated example was used to introduce underspecified models and basic debugging of Essence specs.

**Comment by ozgurakgun** [comment]
The underspecification is to do with the domains of S and M, right? In which case a very light editing of the text should be enough. Is there anything else that needs changing?

**Comment by ozgurakgun** [comment]
That is f(S) and f(M), of course. Not S and M themselves.

**Comment by ott2** [comment]
Have copy-edited; looks good.  The docsday branch should perhaps be merged to master now, as it has settled down?
