### ISSUE TITLE
Multiple problems in min of a quantified expression

### ISSUE THREAD

**Issue by may1066** [conjure-cp/conjure#400]
Consider the following model. it has no solutions. The problem is the `connections[i]!=-1`. In the refinement, it seems to require that `connections[i]!=-1` is true for all `i`, not just (as I guess it should be) at least one `i`.

There is I think a second bug -- the `min` skipping (where it filters out values it doesn't want) seems to pick the smallest value in the domain when connections[i]=-1, I think it should be the largest value in the domain instead.

P.S. this is Chris
```
language Essence 1.3
find connections: matrix indexed by [int(1..3)] of int(-2..25)

such that 
connections[1] = -1,
connections[3] = 2,
connections[2] = min([connections[i] | i <- [1,3], connections[i]!=-1 ]),
```

**Comment by ozgurakgun** [comment]
Yup, can reproduce. With the following workaround:

```
language Essence 1.3
find connections: matrix indexed by [int(1..3)] of int(-2..25)

such that 
connections[1] = -1,
connections[3] = 2,
connections[2] = min([connections[i] | i : int(1,3), connections[i]!=-1 ]),
```

You get a solution that is

```
language Essence 1.3

letting connections be [-1, 2, 2; int(1..3)]
```

This is an undefinedness issue believe it or not!

And the smallest value is dontCare, so that part should be ok.

cc @ChrisJefferson 

PS: I could tell it wasn't Alice even if you didn't tell me :)

**Comment by ozgurakgun** [comment]
Roughly what happens is:

```
min([connections[i] | i <- [1,3], connections[i]!=-1 ])

  ~~>

min(flatten([ [ connections[1] | connections[1] != -1 ]
            , [ connections[3] | connections[3] != -1 ]
            ]))

  ~~>

min( min([ connections[1] | connections[1] != -1 ])
   , min([ connections[3] | connections[3] != -1 ])
   )
```

The second transformation introduces undefinedness :(

It is essentially `min(min([]), min([2]))`, which doesn't (and shouldn't) evaluate to 2. We'll have to think about a better way of handling this (and special-casing constant matrices wouldn't work since this needs to work for any decision variable `m` instead of `[1,3]`).

Now I can go home :)

**Comment by ChrisJefferson** [comment]
I've been thinking about this, I can think of two methods of attack.

One is we could always transform i <- m into "introduce local letting m : matrix indexed by T of U", and then replace `i <- m` with `j : T` and all `i` with m[j]`. However, that might not work well when you have nested quantifiers, unless you can introduce a local letting mid-quantifier.


The second method of attack would be to do kind-of what you are doing already, so something like:

`min([c | i <- m, p(i)])` into `min([ [maxofdom(m), c; int(0..1)][p(i)] | i <- m ])`. Now, this would produce the correct answer, except of course in the case where nothing satisfies `p(i)`. In that case we can use the fact that X/toInt(Y) is equivalent to "X, unless Y is false then it's undefined", and put a "exists i. p(i)" at the bottom.

Do those two both make sense? I feel like the second might be a better route of attack. In general having a way of doing "x if y in true, else undefined" might be a nice thing, we could just teach savilerow that `/toInt(Y)` does that.
