### ISSUE TITLE
Can't quantify over a flatten?

### ISSUE THREAD

**Issue by may1066** [conjure-cp/conjure#401]
[x was a 2-dimensional matrix.
This also doesn't work with x[0] instead of flatten(x)]

"""
Generating models for connected_maze.essence
conjure: This should never happen, sorry!

However, it did happen, so it must be a bug. Please report it to us!

Conjure is actively maintained, we will get back to you as soon as possible.
You can help us by providing a minimal failing example.

Also include the repository version for this build: d94ecc6a2 (2018-09-13 15:21:58 +0100)

Issue tracker: http://github.com/conjure-cp/conjure/issues

Comprehension contains unsupported generators.
    [toInt(i = 0) | i <- flatten(x)]
    Context #1: sum([toInt(i = 0) | i <- flatten(x)])
    Context #2: z = sum([toInt(i = 0) | i <- flatten(x)])

CallStack (from HasCallStack):
  error, called at src/Conjure/Bug.hs:21:15 in conjure-cp-2.2.0-4TKOl8wTeFAKyBqAFABpjt:Conjure.Bug
  bug, called at src/Conjure/UI/Model.hs:766:26 in conjure-cp-2.2.0-4TKOl8wTeFAKyBqAFABpjt:Conjure.UI.Model
"""

**Comment by ozgurakgun** [comment]
I am pretty sure you don't have this any more, but will ask just in case: do you have the input that was causing this message?

**Comment by SaadAttieh** [comment]
Guessing here, I think flatten returns a matrix and it does not look like conjure has a quantifier generator for matrices.  This gives a “this should never happen”:
```
find m : matrix indexed by [int(1..5)]  of int(1..5)
such that forAll i in m . i = 1 
conjure: This should never happen, sorry!
...
...
Issue tracker: http://github.com/conjure-cp/conjure/issues


Comprehension contains unsupported generators.
    [i = 1 | i <- m]
    Context #1: and([i = 1 | i <- m])

```

**Comment by ozgurakgun** [comment]
Thanks @SaadAttieh - I added a couple more examples as regression test cases and will push a fix soon.
