### ISSUE TITLE
Large one dimensional function param takes far to long to parse 

### ISSUE THREAD

**Issue by SaadAttieh** [conjure-cp/conjure#406]
example knapsack and knapsack param attached. 
[large.zip](https://github.com/conjure-cp/conjure/files/2914747/large.zip)

**Comment by ozgurakgun** [comment]
Oh I see this was here as well! Is this the same issue, if so can we close it?

**Comment by SaadAttieh** [comment]
oh whoops, didn't realise this was here. Closing now.
