### ISSUE TITLE
IDE - Linting mode for VSCode Extension

### ISSUE THREAD

**Issue by Revilotom** [conjure-cp/conjure#410]
We could have a mode:

```
conjure ide --lint model.essence
```
That lints and returns a list of error objects (JSON) :
```
[
    {
        "message": "The error message",
        "severity": 0, // Im not sure if warnings are applicable to Conjure? If not then leave this out.
        "startLine": 0,
        "startCol": 0,
        "endLine": 5,
        "endCol": 5
    }
...
]
```

**Comment by ozgurakgun** [comment]
I think we should just use `conjure pretty X.essence` for this for now - this would take too much time (that I won't have in the coming weeks...).

That command will produce an error message or a "pretty printed" version of the input if there are no errors. The printing will remove comments which is not great, I can look into maintaining them at some point.

**Comment by ozgurakgun** [comment]
`conjure type-check X.essence` might work even better for this. No output if everything goes well, an error message to be shown to the user otherwise.
