### ISSUE TITLE
IDE - Type querying for hovers in VSCode Extension

### ISSUE THREAD

**Issue by Revilotom** [conjure-cp/conjure#411]
We could have a mode:
```
conjure ide --getType model.essence <nameOfType>
```
That could return the type of a decision variable within the model:
```
"set of set of int(1..10)"
```

**Comment by Revilotom** [comment]
@ozgurakgun  This doesn't seem to include lettings? Is this on purpose?

**Comment by ozgurakgun** [comment]
This should be better, see the example in the commit.

**Comment by ozgurakgun** [comment]
ditto #417

**Comment by ozgurakgun** [comment]
We will add a textual description field to be used by the IDE for hovers. And a isValidEssence boolean field to say whether the description is intended to be valid Essence (and hence should be highlighted as E) or not.
