### ISSUE TITLE
Inconsistency when getting size of enum domains,

### ISSUE THREAD

**Issue by SaadAttieh** [conjure-cp/conjure#413]
given a domain like
`letting E be new type enum {a, b, c, d, e}`

First, it seems like `|E|` does not work in any context.
```
|`E`|
```
seems to work when used in another domain constructor like 
```
find a : int(1..|`E`|)
```

but not when used in a constraint
```
find a : int... such that a = |`E`|
```

**Comment by ozgurakgun** [comment]
Please reopen if needed @SaadAttieh.
