### ISSUE TITLE
Add type checking for multiple objectives, lex ordered.

### ISSUE THREAD

**Issue by SaadAttieh** [conjure-cp/conjure#419]
```
find a,b,c, : int(1..5)
minimising (a,b,c)
$or maximising (a,b,c)
```

**Comment by fraser-dunlop** [comment]
I'm working on a flattenLex branch for symmetry ordering. We can use that machinery to flatten whatever is in an objective to a 1-D matrix. Is that what we want?

**Comment by ozgurakgun** [comment]
No no, this is unrelated. We will just pass this on to SR.

**Comment by ozgurakgun** [comment]
The Conjure part of this is done now (modulo any bugs you may find).

Please pester your friendly local Savile Row developer for SR support if needed.

**Comment by fraser-dunlop** [comment]
Great!

**Comment by pwn1** [comment]
I don't know where you'll find a friendly _local_ SR developer.
