### ISSUE TITLE
Push fromSolution inwards

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure#422]

**Comment by ozgurakgun** [comment]
@gokberkkocak 

Do you have an example Essence file where the output fromSolution contains anything other that a reference to a decision variable?

**Comment by gokberkkocak** [comment]
It should be pushed outwards not inwards.

For a specific nested case like matrix in a record, the second indexing left inside of fromSolution in dominance relation which causes the problem. 

Simple reproduce;

```
find x,y : record { s : set (minSize 2, maxSize 3) of int(1..5), v : matrix indexed by [int(0..1)] of int(1..2) }
such that x[s] subset y[s]
dominance_relation x[s] subsetEq fromSolution(x[s]) -> x[v][1] > fromSolution(x[v][1])  
```
Dominance becomes;
```
dominance_relation(sum([toInt(x_s_Occurrence[q6]) | q6 : int(1..5)]) <=
                     sum([toInt(fromSolution(x_s_Occurrence)[q7]) | q7 : int(1..5)])
                     /\ and([x_s_Occurrence[q5] -> fromSolution(x_s_Occurrence)[q5] | q5 : int(1..5)])
                     -> x_v[1] > fromSolution(x_v[1]))
```

**Comment by pwn1** [comment]
If this is difficult in Conjure, I think it is probably not difficult in Savile. I can relax the definition of fromSolution to mean that any decision-variable identifier inside it should be treated as coming from the solution, and when doing the replacement just scan up the tree to see if the current node is contained in a fromSolution.

**Comment by ozgurakgun** [comment]
Thanks Pete, should be fixed now. @gokberkkocak please reopen if needed.
