### ISSUE TITLE
This should never happen error acp_summe_school_1

### ISSUE THREAD

**Issue by tarbaig** [conjure-cp/conjure#431]
Hi I was told to give a note when this error happens :-)
-----------------------------------------------------------------------
Input source:

letting x,y be domain int(1..10)
find s : set {x,y}
such that x<y

----------------------------------------------------------------------------
conjure: This should never happen, sorry!

However, it did happen, so it must be a bug. Please report it to us!

Conjure is actively maintained, we will get back to you as soon as possible.
You can help us by providing a minimal failing example.

Also include the repository version for this build: 16c3e4ba9 (2019-06-28 11:36:06 +0100)

Issue tracker: http://github.com/conjure-cp/conjure/issues

textToRepresentation: x

CallStack (from HasCallStack):
  error, called at src/Conjure/Bug.hs:21:15 in conjure-cp-2.3.0-CQD0t6kmkwP5XdZBn1RXtN:Conjure.Bug
  bug, called at src/Conjure/Language/Domain.hs:911:28 in conjure-cp-2.3.0-CQD0t6kmkwP5XdZBn1RXtN:Conjure.Language.Domain

**Comment by tarbaig** [comment]
Conjure: The Automated Constraint Modelling Tool
Release version 2.3.0
Repository version 16c3e4ba9 (2019-06-28 11:36:06 +0100)

**Comment by ozgurakgun** [comment]
Terrible error message! Thanks!

**Comment by ozgurakgun** [comment]
Now it says:

```
Error:
    431.essence:2:14:
unexpected {
expecting ( or of
    find s : set {x,y}
                 ^
```
