### ISSUE TITLE
symmetric constraint on relation parameter is not checked

### ISSUE THREAD

**Issue by gadevoi** [conjure-cp/conjure#432]
When given a relation as a parameter, I am unable to add the constraint that the relation should be symmetric.
For instance, running this model for the graph 4-colouring problem
```essence
$ graph 4-coloring problem
given
  countries new type enum,
  borders : relation (irreflexive, symmetric) of (countries*countries)

where symmetric(borders)
such that symmetric(borders)

letting colours be new type enum {red, blue, green, yellow}

find f: function (total) countries --> colours
such that forAll (c,d) in borders . f(c) != f(d)
```

with the following parameters:
```essence
letting countries be new type enum {a,b}
letting borders be relation( (a,b) )
```

I get the solution `letting f be function(a --> red, b --> blue)`, even though the input relation `borders` is not symmetric.

**Comment by ozgurakgun** [comment]
Thanks!

**Comment by ozgurakgun** [comment]
@gadevoi -- this is now fixed. I added your example as a regression test as well.
