### ISSUE TITLE
This should never happen, sorry! Summer School

### ISSUE THREAD

**Issue by librallu** [conjure-cp/conjure#433]
**The error I got:** 

Generating models for simple.essence
conjure: This should never happen, sorry!

However, it did happen, so it must be a bug. Please report it to us!

Conjure is actively maintained, we will get back to you as soon as possible.
You can help us by providing a minimal failing example.

Also include the repository version for this build: 8260a3356 (2019-06-30 18:55:08 +0100)

Issue tracker: http://github.com/conjure-cp/conjure/issues

Comprehension contains decision expressions as conditions.
    [i | i : int(0..10), x_Occurrence[i]]
    Context #1: product([i | i : int(0..10), x_Occurrence[i]])
    Context #2: product([i | i : int(0..10), x_Occurrence[i]]) = 6

CallStack (from HasCallStack):
  error, called at src/Conjure/Bug.hs:21:15 in conjure-cp-2.3.0-6wU2ArK4uNvAPRrzGLsyfq:Conjure.Bug
  bug, called at src/Conjure/UI/Model.hs:931:26 in conjure-cp-2.3.0-6wU2ArK4uNvAPRrzGLsyfq:Conjure.UI.Model

**Conjure version:**
Conjure: The Automated Constraint Modelling Tool
Release version 2.3.0
Repository version 8260a3356 (2019-06-30 18:55:08 +0100)

**Model:**
language Essence 1.3
find x : set(size 3) of int(0..10)
such that sum(x) = 6, product([i | i <- x]) = 6

**Comment by ozgurakgun** [comment]
product on sets seems broken. thanks for the report!

**Comment by ozgurakgun** [comment]
After a long wait, I can tell you the solution is `{1,2,3}` :)
