### ISSUE TITLE
Bad output from broken input

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure#439]
I accidentally wrote this. It's (I think) wrong, but it outputs savile row which then produces a confusing error -- notice I'm asking if the an enum is in a set.

```

letting atom be new type enum { A, B, C }  

find used : set of atom

such that atom in used
```

**Comment by ozgurakgun** [comment]
It now says:

```
Error:
    In a 'such that' statement: atom in used
    Error: Expected an expression, but got a domain: atom
```

See [file from test](https://github.com/conjure-cp/conjure/blob/73033aabd79836d3ab659522967b5cb82a57ec62/tests/custom/issues/439/stderr.expected).

How do you like it?
