### ISSUE TITLE
Using undefined enum-values in function declarations over enums produces "This should never happen"

### ISSUE THREAD

**Issue by CodingCellist** [conjure-cp/conjure#440]
If you have an `essence` file containing:
```
letting my_enum be new type enum { E1, E2 }

given my_function : function (total) my_enum --> int
```
And a `param` file containing:
```
letting my_function be function ( E3 --> 1 )
```
(i.e. using a value not specified in the enum), conjure produces a "This should never happen" error instead of saying that the value `E3` is not in `my_enum` or that the declared type of `my_function` and the actual function don't match or similar.

E.g. files: [enum-function-bug.zip](https://github.com/conjure-cp/conjure/files/3382794/enum-function-bug.zip)

**Comment by ozgurakgun** [comment]
Thanks! This is indeed ugly.

I think the easy thing to do is to say E3 is not defined. I'll just do that.

**Comment by ozgurakgun** [comment]
Thanks for reporting @CodingCellist - I think the output is a bit better now. I'll close the issue, please let me know if you have a suggestion for a better message.
