### ISSUE TITLE
parameter-generator: updates on relation's cardinality

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#449]
There are a number of things I'd like to propose for changes, regarding `conjure parameter-generator` for relation's cardinality
- `cardMiddle` is still set as MAXINT at the moment, we'd want to update it as MAXINT*MAXINT
- perhaps `cardDelta` can be set as MAXINT/2 instead of 3. Hopefully irace will be able to narrow it down when needed. The same changes can be applied to other delta variables.
- `maxSize` for relation can be removed, as the size will be controlled by `cardMiddle` anyway
- the changes for relation are on streamlining branch only at the moment. Do we want to have them in master also?

Thanks :)

**Comment by ozgurakgun** [comment]
@ndangtt can you please test this and reopen the issue if I made a mistake or missed something? Thanks.

**Comment by ndangtt** [comment]
I would set `cardDelta` to MAXINT/2 instead. Currently it is set as MAXINT*MAXINT/2, which might be probably too large.

**Comment by ozgurakgun** [comment]
I thought the idea was, say in a function's range, having anything smaller than the full range for delta would mean this is necessarily incomplete.

**Comment by ndangtt** [comment]
That is a good point! 

In this case this is for cardinality, so if the relation is standing alone, it should be fine having `cardDelta` set to MAXINT/2.

However, in the case where we have nested structure, like `set of relation of int(1..m)*int(1..n)`, then restricting the `cardDelta` of the inner relation to MAXINT/2 would indeed make the outer-set incomplete.

So yes I agree with you about having `cardDelta` as set MAXINT*MAXINT/2 :)

**Comment by ozgurakgun** [comment]
irace just needs to get better at sampling these large domains :)
