### ISSUE TITLE
More bugs with `catchUndef` and `min` 

### ISSUE THREAD

**Issue by SaadAttieh** [conjure-cp/conjure#454]
There is a similar issue that talks about catchUndef of a min of an empty set not passing through the type checker.  This is a bit different, this passes the type checker and even works correctly with validate solution, but conjure produces the wrong model.  I realise that `catchUndef` was not originally intended for user input but I have, a few times, come across a situation where it would be nice.  A some what silly but small example below:

```
find a : int(-1..5)
find b : int(1..5)
such that 
a = min([i | i : int(1..5), i > b]),
b > 5
```

**Comment by ozgurakgun** [comment]
I think it actually does the right thing here, doesn't it?

The list is empty, hence the min is undefined, hence the constraint is undefined. Am I wrong?

**Comment by SaadAttieh** [comment]
My apologies, I forgot to put the catchUndef. 
```
find a : int(-1..5)
find b : int(1..5)
such that 
a = catchUndef(min([i | i : int(1..5), i > b]),-1),
b > 5

```

**Comment by SaadAttieh** [comment]
output:
```
Generating models for test.essence
Generated models: model000001.eprime
Saved under: conjure-output
Savile Row: model000001.eprime
Error:
    Savile Row stdout: ERROR: catchUndef must have a constant as the second argument: catchUndef(conjure_aux1, (-1))

    Savile Row stderr: ERROR: Failed type checking after substituting in lettings.

    Savile Row exit-code: 1


```

**Comment by ozgurakgun** [comment]
Now catchUndef doesn't think -1 is a constant.

`catchUndef must have a constant as the second argument: catchUndef(conjure_aux1, (-1))`

@pwn1 ?

**Comment by ozgurakgun** [comment]
Sorry I didn't say it there, but this message is coming from SR.

**Comment by SaadAttieh** [comment]
Cheers Oz.   That’s one thing solved.  Now I believe that SR does understand that 0 is a constant.  So if I edit the input essence file to use 0 in the catchUndef, I get no solutions.
So yes, using 0 in the catchUndef along with fixing an error I made 
`b > 5`
should be
`b > 4`

We get one solution, the correct solution :).

I think this is because

**Comment by ozgurakgun** [comment]
The following seems to solve the SR issue. I'll leave it to @pwn1 to decide if this should go in or not.

```
diff --git a/src/expression/UnaryMinus.java b/src/expression/UnaryMinus.java
index facfba25b..99fb93994 100644
--- a/src/expression/UnaryMinus.java
+++ b/src/expression/UnaryMinus.java
@@ -101,6 +101,12 @@ public class UnaryMinus extends Unary
     }
 	
 	public boolean toFlatten(boolean propagate) { return !CmdFlags.getDominiontrans();}  // depends on target
+
+    @Override
+    public boolean isConstant() {
+        return getChild(0).isConstant();
+    }
+
 	public boolean isNumerical() {
         return true;
     }
```

**Comment by ozgurakgun** [comment]
Actually I pushed this: https://github.com/savilerow/savilerow-main/commit/41dfde19d1a526b817cce68f3ca6afb638cd99ad

@pwn1 please feel free to revert!

**Comment by pwn1** [comment]
That breaks assumptions in SR. In particular if isConstant returns true, then it is possible to call getValue. Instead can you change the typecheck method of CatchUndef to check something like this:
getChild(1).getCategory()==ASTNode.Constant
instead of:
getChild(1).isConstant()
?

**Comment by ozgurakgun** [comment]
Ooooh apologies for pushing it without getting input from you in that case!
I am happy to do that instead if you like.

**Comment by pwn1** [comment]
That's alright, I'm being really useless at maintaining SR right now so fine for you to have a go. 
I have done it.

**Comment by pwn1** [comment]
I didn't test it... at all... let me know if it doesn't work!

**Comment by ozgurakgun** [comment]
@SaadAttieh I am closing this now, please reopen if there is a problem!
