### ISSUE TITLE
Allow in (or :?) for all quantification

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure#461]
At the moment we write forAll x : T, for types, but forAll x in S, for sets. I think it would be easier if we could use 'in' for both.

The other option we be to push all tutorials towards matrix comprehension?

**Comment by ozgurakgun** [comment]
Same problem with comprehensions. `<-` works for expressions, `:` for domains there.

**Comment by ott2** [comment]
It would seem to make sense to treat ``x in T`` as a synonym for ``x : T`` when ``T`` is a type, and ``[f(x) | x <- D]`` as a synomym for ``[f(x) | x : D]`` when ``D`` is a domain?

**Comment by ozgurakgun** [comment]
I'll close this as won't fix for now, we can think about this in the future again if we get to rethinking the language...
