### ISSUE TITLE
for each given, we classify it with one of size or not

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure#464]

**Comment by ozgurakgun** [comment]
Hi @ndangtt -- where should these end up?

There are two places, the Essence file and the irace file. I guess we just want to attach this to one of them (or alternatively we can introduce a 3rd file?)

```
$ cat problem.essence
given a,b : int(1..10)
given x : set of int(a..b)

$ conjure parameter-generator problem.essence --essence-out problem-gen.essence

$ grep given problem-gen.essence
given a_middle: int(1..10)
given a_delta: int(0..4)
given b_middle: int(1..10)
given b_delta: int(0..4)
given x_cardMiddle: int(0..100)
given x_cardDelta: int(0..50)
given x_inner_middle: int(1..10)
given x_inner_delta: int(0..4)

$ cat problem-gen.essence.irace
a_middle "-a_middle " i (1, 10)
a_delta "-a_delta " i (0, 4)
b_middle "-b_middle " i (1, 10)
b_delta "-b_delta " i (0, 4)
x_cardMiddle "-x_cardMiddle " i (0, 100)
x_cardDelta "-x_cardDelta " i (0, 50)
x_inner_middle "-x_inner_middle " i (1, 10)
x_inner_delta "-x_inner_delta " i (0, 4)

```

**Comment by ndangtt** [comment]
We could put that in the irace param file I suppose. Parameters controling size will have type ` i,log `, while the rest have type ` i `. 

Later on we can add some additional sampling strategies besides `log`. The choice between `log` and other strategies can be specified as a flag for `conjure parameter-generator`.

Would those make sense to you? :)

**Comment by ozgurakgun** [comment]
Yes, very sensible. Coming up next :)
