### ISSUE TITLE
issue with letting and set

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#473]
(apology for the uninformative issue's title, please feel free to change it as you wish!)

I have the following model and param files:

```
$ model.essence
given a new type enum
letting aD be toSet([x | x : a])
find x: set of a
such that x = aD
```

``` 
$ test.param
letting a be new type enum {a1,a2,a3}
```

`conjure solve model.essence test.param` gives an error message `Comprehension contains unsupported generators.`

But if I change `model.essence` to:
```
$ model.essence
given a new type enum
find x: set of a
such that x = toSet([x | x : a])
```

Then it's fine. I'm wondering if this might be a bug, or if my first model's syntax is incorrect?

**Comment by ozgurakgun** [comment]
walks like a bug, talks like a bug, must be a bug :)

**Comment by ott2** [comment]
The two should not differ.  However, I would have expected `given a new type enum` to be flagged as an error, should it not be `given a : new type enum` instead?

**Comment by ndangtt** [comment]
@ott2: `given a new type enum` works for me. I'm not sure why `:` is not needed though. I actually just followed examples on CSPLib to define `new type enum`, such as the following one:
http://www.csplib.org/Problems/prob036/models/FixedLengthErrorCorrectingCodes.essence.html

**Comment by SaadAttieh** [comment]
haha I laugh because I get confused with this all the time. I think that in this case, the `:` should not be there.  `:` denotes domains whilst this is a type?  Or actually I guess it is a domain?  
…

Hmmm 
...


>

**Comment by ozgurakgun** [comment]
This is fixed, but I expect other similar issues. Please report if you come across any. I really should tidy the handling of lettings at some point.
