### ISSUE TITLE
Unparseable input for the new json output format 

### ISSUE THREAD

**Issue by JoanEspasa** [conjure-cp/conjure#478]
Good morning!

Thanks for adding the simple JSON output, it helps quite a lot!. However, I think I found a rather simple bug. I try to re-parse a solution given by conjure using

`conjure pretty --output-format=json sol.solution`

and it errors saying:
```
Parsing as a parameter file 
Error: 
    Cannot convert the following to simple JSON: 
    0 - 65536
```

I attach the solution here. I also updated conjure quite recently:
```
Release version 2.3.0
Repository version 80d59db27 (2020-03-14 12:09:56 +0000)
```
[sol.txt](https://github.com/conjure-cp/conjure/files/4386510/sol.txt)

Thanks :)

**Comment by ozgurakgun** [comment]
Can you please test this @JoanEspasa?

**Comment by JoanEspasa** [comment]
Now its working fine, thanks @ozgurakgun :)
