### ISSUE TITLE
parameter-generator for boolean functions: a new rewriting rule with percentages

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#480]
Hi Oz,

With the current rewriting rules for `function`, there is nothing created in the generator spec for the range of a `boolean function`, so the tuning can't control the range of variables of those types. We'd like to propose a rewriting rules for this type of variable using percentage, where we control the percentage of true values in the function. Below is an example:

`given a: function int(1..50) --> bool`

This should be rewritten as:
```
given a_percentage: int(0..100)
such that
   sum([toInt(q[2]=true) | q <- a]) = a_percentage * |defined(a)| / 100
```
(for brevity, I omitted here all the middle and delta parameters for domain and cardinality of `function a`)

Please find in attachment a minimal example with one total function, and one partial function. The files include:
- A problem spec and expected generator spec
- An example param and a solution for the generator spec

Thank you!

[gen.essence.txt](https://github.com/conjure-cp/conjure/files/4470562/gen.essence.txt)
[gen-test.param.txt](https://github.com/conjure-cp/conjure/files/4470563/gen-test.param.txt)
[gen-test.solution.txt](https://github.com/conjure-cp/conjure/files/4470564/gen-test.solution.txt)
[model.essence.txt](https://github.com/conjure-cp/conjure/files/4470565/model.essence.txt)

**Comment by ozgurakgun** [comment]
Should percentage be log or linear?

**Comment by ozgurakgun** [comment]
Also, do we really want it to be `=`? What if the function was from 7 values? i.e. `int(1..7) --> bool`

Why don't we make this an absolute number? Why a percentage?

**Comment by ozgurakgun** [comment]
Or a range I suppose...

**Comment by ndangtt** [comment]
Wow, thank you so much for doing those so quickly Oz!! :D 

1. You're right, a range of absolute values can be an alternative indeed. I decided to go for a single percentage value for our first set of experiments because it's simpler for the current tuning setup:
- only one parameter to tune
- we don't have to worry about sampling min/max such that min<=max
- when we tune (the range of) the number of true-elements directly, it increases the likelihood of having unsat generator params because those values must be compatible with the other parameters (min/max of function's domain & min/max of function's cardinality). We don't have this issue with the percentage.

2. I'm planning to try log-scale for everything for now, so that's fine! :D

3. Regarding you remark on `=` and `int(1..7) --> bool`, I think it's okay. Different percentage values may produce the same results and the tuning should be fine with it :)

**Comment by ott2** [comment]
One problem with percentage or range or even a single number as a cardinality constraint, in general: adding such constraints can make the resulting generator instance *extremely* difficult to solve.  In particular, I think this can make the instance \#P-hard, which is nearly as difficult as the general planning problem (which is PSPACE-hard).

**Comment by ozgurakgun** [comment]
We often don't have any other constraints on a function like this. So we would just be telling to solver to set n of them to true, right? I don't expect that to cause any difficulty (again, assuming no other non-trivial constraints here).

**Comment by ndangtt** [comment]
Yah I agree with Oz. The ones created by the rewriting rules are generally easy to solve. 
The concern is true when we start adding complicated `where` statements in the problem's Essence spec. For planning we do have quite a few `where` statements, we'll see if they make the generator harder to solve in that case :)

**Comment by ndangtt** [comment]
Since we have the repairing now, having percentage as a range is probably a good idea :D
```
$ model.essence
given f: function int(1..10) --> bool
```
```
$ model-instanceGenerator.essence
...
given f_percentage_min: int(0..100)     $ new changes
given f_percentage_max: int(0..100)     $ new changes
...
such that
    sum([toInt(q1[2]) | q1 <- f]) >= f_percentage_min * |defined(f)| / 100, $ new changes
    sum([toInt(q1[2]) | q1 <- f]) <= f_percentage_max * |defined(f)| / 100, $ new changes
...
```
```
$ model-instanceRepair.essence
...
given f_percentage_min: int(0..100)
given f_percentage_max: int(0..100)
find repaired_f_percentage_min: int(0..100)
find repaired_f_percentage_max: int(0..100)
...
minimising
    sum([|repaired_f_cardMin - f_cardMin|, |repaired_f_cardMax - f_cardMax|, |repaired_f_defined_min - f_defined_min|,
         |repaired_f_defined_max - f_defined_max|, |repaired_f_percentage - f_percentage|,
         $ new changes
         |repaired_f_percentage_min - f_percentage_min|, |repaired_f_percentage_max - f_percentage_max|;     
             int(1..7)])     

```
