### ISSUE TITLE
`parameter-generator`: conjure hangs when a `where` statement is added

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#481]
Hi Oz,

When I run 
```
conjure parameter-generator model.essence --essence-out generator.essence
```
for the attached mode, `conjure` seems to hang (I let it run ~ 30mins and it's still running). But when I comment out the `where` statement on the last line of `model.essence`, the command finishes within minutes. 

Sorry for the relatively large example model. It seems that if I reduce the amount of elements in the `where` statement to only a few of them, then `conjure` can finish, but still, it takes much more time than without having that `where` statement, which is a bit surprising, as I thought `conjure` will just simple replace the keywords `where` by `such that`. Could you please help to have a look at it?

Thank you!

[model.essence.txt](https://github.com/conjure-cp/conjure/files/4517283/model.essence.txt)

**Comment by ozgurakgun** [comment]
This is still not great, but it finishes in ~6 minutes for me now. I'll close the issue. Please reopen (or open new issues) when there are other cases like this one.

**Comment by ndangtt** [comment]
That's good enough I think! Thanks very much for fixing it Oz! :D

**Comment by ndangtt** [comment]
Hi Oz!

We have another model that has a similar issue. It is a classical planning problem called *barman*. 
When I do
```
conjure parameter-generator barman.essence --essence-out generator.essence --MAXINT=30
```
conjure runs for 30 mins and exited with error messages:
```
conjure: Heap exhausted;
conjure: Current maximum heap size is 4294967296 bytes (4096 MB).
conjure: Use `+RTS -M<size>' to increase it.
```
When I remove the `where` statements, the command finishes in about 6 mins.

Could you please help to have a look at it?

Thank you!

[barman.essence.txt](https://github.com/conjure-cp/conjure/files/4548027/barman.essence.txt)

**Comment by ozgurakgun** [comment]
Locally:

```
~/repos/github/conjure/tests/custom/issues/481> time conjure parameter-generator barman.essence --essence-out generator.essence --MAXINT=30

real	0m59.729s
user	0m58.449s
sys	0m0.508s
```

I'll push once the tests finish running.

**Comment by ndangtt** [comment]
That's awesome! Thanks very much Oz!
