### ISSUE TITLE
`parameter-generator`: upper bound of cardinality for partial function

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#482]
Hi Oz,

I noticed that when we have a partial function like this:
```
given f: function int(1..10) --> int(1..)
```
The range of cardinality params created by `conjure parameter-generator` are up to MAXINT (as listed below). Would that make sense and be simple enough to have their ranges as up to the maximum size given in the problem spec instead?
```
given f_cardMiddle: int(0..100)  $ expected: int(0..10)
given f_cardDelta: int(0..50)   $ expected: int(0..4)
given f_defined_middle: int(1..10)
given f_defined_delta: int(0..4)
```
I understand that if `f` is defined as `given m: int(1..); given f: function int(1..m) --> int(1..)`, then it makes sense to have `f_cardMiddle: int(0..100)` and `f_cardDelta: int(0..50)` and having additional constraints added to limit their range to m. But in this particular case, the size is given at the beginning, so we can limit the range in advance.

Please find in attachment the essence model, the currently generated generator spec and the expected generator spec.

Thank you!
Nguyen

[gen.essence.irace.txt](https://github.com/conjure-cp/conjure/files/4522988/gen.essence.irace.txt)
[gen.essence.txt](https://github.com/conjure-cp/conjure/files/4522989/gen.essence.txt)
[gen-new.essence.irace.txt](https://github.com/conjure-cp/conjure/files/4522990/gen-new.essence.irace.txt)
[gen-new.essence.txt](https://github.com/conjure-cp/conjure/files/4522991/gen-new.essence.txt)
[model.essence.txt](https://github.com/conjure-cp/conjure/files/4522992/model.essence.txt)

**Comment by ozgurakgun** [comment]
Can you please check that this does what you wanted @ndangtt? See the commit that closes this issue to see the test case.

https://github.com/conjure-cp/conjure/commit/a0a9c7d5fe795d5d5ef0a6ddb4a3bdec31f2c3fa

**Comment by ndangtt** [comment]
Yes it is exactly what we expected. Thank you very much Oz! :D

**Comment by ndangtt** [comment]
My apology, now I realised that the example I posted was actually not good :(

We would want upper bound of cardinality to be maxDomain-minDomain+1.
Example:
```
given f: function int(-5..10) --> int(1..)
```
Expected generator spec
```
given f_cardMin: int(0..15)  $ domain currently generated: int(0..10)
given f_cardMax: int(0..15)  $ domain currently generated: int(0..10)
```

Could you please help to check it again?

Thank you!!!
Nguyen

**Comment by ozgurakgun** [comment]
I suspect you mean 16 :)

**Comment by ndangtt** [comment]
Oops, indeed! Thank you for correcting and fixing it!! :D
