### ISSUE TITLE
Conjure generating many redundant constraints for CVRP

### ISSUE THREAD

**Issue by SaadAttieh** [conjure-cp/conjure#484]
When modelling CVRP (attached), I noticed the following redundant  constraints.  From what I can tell from the minion output, the second one is eliminated, the first one is not.  These could be potentially quite expensive as it looks like we generate \(n^2\) of these constraints, n=numberLocations.

It amounts to basically,
```
a <= b -> a-1 <= b
```
The second one, which I think is caught,

```
a <= b -> a <= b
```

 I would have been surprised if SR had been programmed to catch the first one, though maybe it should?  I remember discussing this years ago, something about Conjure having to include these constraints for a different reason.

```
    and([q13 <= plan_ExplicitVarSizeWithMarkerR15_Marker ->
         and([q1 <= plan_ExplicitVarSizeWithMarkerR15_Values_ExplicitBounded_Length[q13] ->
              q1 - 1 <= plan_ExplicitVarSizeWithMarkerR15_Values_ExplicitBounded_Length[q13]
                  | q1 : int(2..numberLocations)])
             | q13 : int(1..numberLocations)]),
    and([q13 <= plan_ExplicitVarSizeWithMarkerR15_Marker ->
         and([q1 <= plan_ExplicitVarSizeWithMarkerR15_Values_ExplicitBounded_Length[q13] ->
              q1 <= plan_ExplicitVarSizeWithMarkerR15_Values_ExplicitBounded_Length[q13]
                  | q1 : int(2..numberLocations)])
             | q13 : int(1..numberLocations)]),

```

**Comment by SaadAttieh** [comment]
[cvrp.essence.txt](https://github.com/conjure-cp/conjure/files/4535157/cvrp.essence.txt)

**Comment by ozgurakgun** [comment]
Not doubting you at all, but I am struggling to find these in the output from a quick look. I attach the E' I get. Can you tell me where they are please?

Once we find them, it would help if we comment out some constraints (from the Essence) that are irrelevant for this problem so the problematic ones in the output are easier to spot and deal with.

[model000001.eprime.txt](https://github.com/conjure-cp/conjure/files/4541166/model000001.eprime.txt)

**Comment by SaadAttieh** [comment]
Hmm, must have been unlucky to land on a bad commit (see below).  Was only a couple weeks back but appears that the model output has changed dramatically since then.
Sorry to trouble you.
```
Release version 2.3.0
Repository version d71df22c3 (2020-04-15 17:26:17 +0100)
```

**Comment by ozgurakgun** [comment]
Grande - please reopen if you notice something like this again. Thanks for reporting.
