### ISSUE TITLE
conjure modelling issue: variable name is used without defined

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#486]
(I don't know what'd be the best title for this issue, so please feel free to change the title as you see fit!)

I have this model:
```
$ model.essence
letting n be 10
find r: record {f : function int(1..100) --> bool}
such that
    and([q13 >= 0 /\ q13 <= n
         <-> q13 in defined(r[f]) | q13 : int(1..400)]),
    and([r[f](var_s)
             | var_s : int(1..100), var_s >= 0, var_s <= n])
```
When I do `conjure solve model.essence`, I get error messages:
```
Error:
    Savile Row stdout: ERROR: Identifier not defined: var_s
    Savile Row stderr: ERROR: Failed type checking after substituting in lettings.
```
This is because the generated `.eprime` model has a line where a variable name `var_s` is used without being defined:
```
$ model.eprime
find r_f_Function1DPartial_Flags: matrix indexed by [int(1..100)] of bool
find r_f_Function1DPartial_Values: matrix indexed by [int(1..100)] of bool
branching on [r_f_Function1DPartial_Flags, r_f_Function1DPartial_Values]
such that
    and([q13 >= 0 /\ q13 <= 10 <-> r_f_Function1DPartial_Flags[q13] | q13 : int(1..400)]),
    and([r_f_Function1DPartial_Values[var_s] | var_s : int(1..100), var_s >= 0, var_s <= 10]),
    r_f_Function1DPartial_Flags[var_s],   $$$ this is the line that causes the error
    and([r_f_Function1DPartial_Flags[q1] = false -> r_f_Function1DPartial_Values[q1] = false | q1 : int(1..100)])
```
If I disable either of the two constraints in the original essence model then it's fine. Could you please help to check it?

Thank you!

**Comment by ozgurakgun** [comment]
This is bizarre! `conjure solve -af` works, yet `conjure solve -ac` (the default) blows up. And there are no decisions to be made, so both of them _should_ follow the same path.

**Comment by ozgurakgun** [comment]
Can you test please @ndangtt?

**Comment by ndangtt** [comment]
Yay, it works now! Thank you Oz! I'm gonna close the issue now :D
