### ISSUE TITLE
conjure asks for CPLEX_PATH even when cplex is added to PATH

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#491]
conjure asks for CPLEX_PATH when calling `conjure solve` although I already have cplex in my PATH. Interestingly when I reverted back to a previous commit `6c29fbde9 (2019-11-19 14:31:13 +0000)`, CPLEX_PATH was no longer required. Is it an expected behaviour? 

```
Error:
    Set environment variable CPLEX_PATH. Something like:
        CPLEX_PATH=/path/to/cplex/library conjure solve
```

**Comment by ozgurakgun** [comment]
Hmm, the old version working out of the box is slightly surprising to me. We were not passing `--cplex-dll` back then, and as far as I remember Minizinc would then only work if the dll was at a specific location. Which in turn means it wouldn't work on MacOS for example.

This is what I have in my .profile file, so I don't have to set the dll path environment variable every time. Can you do something like that too maybe?

`export CPLEX_PATH=/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/libcplex1290.jnilib`

**Comment by ozgurakgun** [comment]
Is this still an issue @ndangtt?
