### ISSUE TITLE
missing param in eprime file

### ISSUE THREAD

**Issue by ndangtt** [conjure-cp/conjure#502]
Hi @ozgurakgun, 

I have the following Essence model:

```
given a,b: int(1..100)
letting c be max({a,b})
letting d be c+5

find x: int(1..100)
such that x=d
```

The output E' model from `conjure modelling -ac` for that model would be:
```
given a: int(1..100)
given b: int(1..100)
letting c be max([a, b; int(1..2)])
find x: int(1..100)
branching on [x]
such that x = d
```

`d` is missing in that E' model, cause `conjure solve` to throw error on any random param file.

Could you please help to have a look at it?

Thank you!

**Comment by ozgurakgun** [comment]
Whaaaaaat

Should be a quick fix, let's see if I break anything else.

**Comment by ozgurakgun** [comment]
Do you want me to update the essence-features branch too?

**Comment by ndangtt** [comment]
Thank you very much for fixing it Oz!!

And yes, it would be great to have it in the essence-features branch too :)
