### ISSUE TITLE
`_` isn't renamed under certain conditions, which Savile Row doesn't like

### ISSUE THREAD

**Issue by stylpe** [conjure-cp/conjure#512]
You can find a repro at https://replit.com/@SuperMikal/Conjure-and-Essence-20220507#feedback/Rename%20_%20for%20Savile%20Row/sudoku.essence , look at line 60 and below (plus the .param in the same folder).

I'm designing a Sudoku solver supporting a broad range of  variant rules. I want to use `_` as an alias for blanks in the given clues. (Optionally, if you have an idea for a better way to design ang implement this, let me know! But I can't use `0` as there are variant rules that use that as an actual digit...)

This works fine, *mostly*. But it turns out that I can't use that alias in certain ways because then it doesn't get refined to a different name, and it looks like Savile Row doesn't accept it as input. A simple `letting x be domain int(_..9)` triggers this behaviour. This is the result:

```
Error:
    Savile Row stdout: 
    Savile Row stderr: letting _ be 0

--------^
ERROR: Parsed 'letting' keyword.
ERROR: Failed when parsing rest of structure following line:18 column:8

    Savile Row exit-code: 1
```

Using Savile Row 1.9.1 (Repository Version: 2ac988043 (2021-09-10 10:51:58 +0100)) and Conjure Release version 2.3.0 Repository version f5233b5b9 (2022-05-03 22:55:23 +0100)

Aside: I'd really like to design a usable flexible config system using `given Config : set of variant { ... }`, but the current form ended up a bit cryptic and unreadable. Would you be open to consider a separate feature request issue for making something like `given x : some_domain with default some_value`, or something more general purpose like an optional type (basically equivalent to `variant { some: my_domain, none: some_sentinel_value }` but with syntax sugar)?

**Comment by ozgurakgun** [comment]
The _ thing is a convenience feature since SR doesn't support it. I'll extend it to support when it's inside a domain.

By the way: I had never used replit before but it looks convenient!

In your aside point you are basically asking for something like a Maybe type (if you are familiar with Haskell). I thought of this, but never had a syntax I was happy with. Not sure I understand your "with default" suggestion fully, can you expand it to a full example please?

I know you said you have a bunch of other issues you've encountered, maybe we can organise a call and go over them? You can email me on my Uni email and we can organise it ozgur.akgun@st-andrews.ac.uk

**Comment by stylpe** [comment]
I immediately found a nicer workaround after posting the issue:
```
letting Blank be min(_valid) - 1
letting _ be Blank
```
Though the issue still stands.

A quick example for the aside: `given ValidDigits : set of int with default {1,2,3,4,5,6,7,8,9}`

The goal is just UX convenience when writing and reading the .param for a Sudoku puzzle, so that you can essentially just write something like "normal Sudoku rules apply" without needing to get explicit. Pretty much analogous to command line parameters.

I want to avoid needing a template .param file because it would not be as easy to see at a glance what the important constraints are, or phrased differently, it would be easy to miss if you changed a single digit when reading the .param for a specific puzzle if the ValidDigits are always specified. 

Also, needing to update old puzzles .params if I introduce new givens later.

And yes, I'd love that! I've started collecting some concrete cases in the feedback folder in that replit, but I want to work on it a bit more first. I'll be in touch, though don't be surprised if you don't hear from me until after summer, I'm terrible at scheduling and time management :P In the mean time, I will keep making issues for clear-cut cases like this one.

**Comment by ozgurakgun** [comment]
So in this case if there is a default in the essence file, that value wouldn't need to be specified in the param file?

How about having multiple param files? You could have a base one and a more specific one. Feed both to Conjure and the later one overrides values from the previous one? Would that work as an alternative design.

(One complication is that `conjure solve` currently accepts multiple param files, but solves them independently. I don't think anyone uses this "feature" and it is equivalent to invoking `conjure solve` multiple times anyway. So I wouldn't mind removing this functionality in favour of the one you/I are proposing here. I believe @ott2 also wanted this in the past.)

**Comment by stylpe** [comment]
Oh, I kinda like that feature while developing the model though, but maybe it could be a separate argument like - - default-params=normalsudoku.params? 

Other than that, a Maybe type would do the trick (and you were right it's exactly what I meant when saying "optional") plus be great to have for other purposes too, along with the [maybe](https://hackage.haskell.org/package/base-4.16.1.0/docs/Data-Maybe.html#v:maybe) function some kind of control structure like basic pattern matching. For me it would be fine to limit its use to non-decision vars.

**Comment by stylpe** [comment]
Another idea: an operator to derive a new record from two or more records (and/or variants?), and support for partial record values, like a variant that lets you specify more than one property. 

Anyways, let's save that for later. I'll build a new binary with your fix later this week and let you know how it goes!

**Comment by ozgurakgun** [comment]
I'll close this issue since the underscore issue is resolved (as far as I can see). We can discuss the other request in a separate issue?
