### ISSUE TITLE
ghcr.io docker images are always last release (2.3.0)

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure#515]
Notice how the ghcr "master" image is the last release of conjure (from 2019).

```
caj/ $ docker run ghcr.io/conjure-cp/conjure:master conjure --version
Conjure: The Automated Constraint Modelling Tool
Release version 2.3.0
Repository version 08dc983cf (2019-06-23 17:51:50 +0300)
```

This is (I guess) because the docker image is hard wired to 2.3.0, even though the ghcr image is rebuilt for master, and branches.

Could it be changed so `master` gives the current master branch?

@ZachNewbery

**Comment by ChrisJefferson** [comment]
I think we need to do something like described here: https://github.com/docker/build-push-action/issues/276

I started doing this (I made the necessary change to the dockerfile) and accidentally pushed it to master (woops!), including breaking the github action. I've undone the change -- but we need to make the change described in that issue to get master commits.

**Comment by ozgurakgun** [comment]
this is fixed
