### ISSUE TITLE
Conjure licence

### ISSUE THREAD

**Issue by ott2** [conjure-cp/conjure#534]
I've been working on a `brew` formula for Conjure. One step requires assigning a licence type, matching one of the identifiers at https://spdx.org/licenses/ and as far as I can tell it is much more likely that the formula will be accepted if we can avoid using the fallback
```
license :cannot_represent
```
which is the only one I can currently match to.

It's not clear to me which of these identified licences best matches the custom licence of Conjure. Any pointers?

**Comment by ott2** [comment]
A reasonably close match is https://creativecommons.org/licenses/by-sa/4.0/ but it's not quite a match.

**Comment by ozgurakgun** [comment]
It is BSD-3 clause at the moment as per the [cabal file](https://github.com/conjure-cp/conjure/blob/master/conjure-cp.cabal#L7).

So I think https://spdx.org/licenses/BSD-3-Clause.html would do?

**Comment by ott2** [comment]
I'll use ``license "BSD-3-Clause"`` then, thank you!
