### ISSUE TITLE
--solutions-in-one-file doesn't move solutions out of conjure-output

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure#535]
If I pass "--solutions-in-one-file", a file called `model00001-<param>.solutions` gets created in the conjure-output directory, but it doesn't get copied out.

The same problem occurs with `--output-format=json`, once again the file is left in `conjure-output`.

**Comment by ozgurakgun** [comment]
Should be done, but it would be great if you can test it.

There is also a new output-format jsonstream. This one prints a solution per line. output-format=json prints an array of solutions. (when used with --solutions-in-one-file)
